# Generated by Django 5.2.5 on 2025-09-11 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('composicao', models.CharField(choices=[('e', 'Entradas'), ('p', 'Principais'), ('s', 'Sobremesas'), ('b', 'Bebidas'), ('o', 'Outros')], default='o')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ingredientes', models.CharField(max_length=500)),
                ('valor', models.PositiveIntegerField()),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurante.tipocomida')),
            ],
        ),
    ]
