# Generated by Django 5.2.5 on 2025-09-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocomida',
            name='status',
            field=models.CharField(choices=[('Entradas', 'Entradas'), ('Principais', 'Principais'), ('Sobremesas', 'Sobremesas'), ('Bebidas', 'Bebidas')], default='Principais'),
        ),
    ]
