# Generated by Django 5.2.5 on 2025-08-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comida', models.CharField(max_length=100)),
                ('ingredientes', models.CharField(max_length=255)),
                ('valor', models.PositiveIntegerField()),
            ],
        ),
    ]
