# Generated by Django 5.2.5 on 2025-09-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_tipocomida_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocomida',
            name='status',
        ),
        migrations.AddField(
            model_name='tipocomida',
            name='composicao',
            field=models.CharField(choices=[('Outros', 'Outros'), ('Entradas', 'Entradas'), ('Principais', 'Principais'), ('Sobremesas', 'Sobremesas'), ('Bebidas', 'Bebidas')], default='Outros'),
        ),
    ]
