# Generated by Django 5.2.5 on 2025-08-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_comida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.AlterField(
            model_name='comida',
            name='ingredientes',
            field=models.CharField(max_length=500),
        ),
    ]
