# Generated by Django 5.2.5 on 2025-09-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_remove_tipocomida_status_tipocomida_composicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocomida',
            name='composicao',
            field=models.CharField(choices=[('e', 'Entradas'), ('p', 'Principais'), ('s', 'Sobremesas'), ('s', 'Bebidas'), ('o', 'Outros')], default='Outros'),
        ),
    ]
