# Generated by Django 5.2.5 on 2025-09-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_alter_tipocomida_composicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocomida',
            name='composicao',
            field=models.CharField(choices=[('e', 'Entradas'), ('p', 'Principais'), ('s', 'Sobremesas'), ('b', 'Bebidas'), ('o', 'Outros')], default='o'),
        ),
    ]
